
using System.ComponentModel.DataAnnotations.Schema;

namespace Api_with_dev_creed.Models
{
    public class Gener
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//as we using byte as a key it will not understand to increesed by him self so we configured it with this code to be generated by its own 
        public byte Id { get; set; }
        [MaxLength(100)]
        public string Name { get; set; }
    }
}
